name: flutter_grocery
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#version: 1.1.1+4  #android
version: 1.0.0+2    #ios

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  provider: ^6.0.2
  http: ^0.13.1
  freezed: ^2.0.3+1
  shared_preferences: ^2.0.5
  photo_view: ^0.14.0
  dio: ^5.1.2
  image_picker: ^0.8.4+8
  pin_code_fields: ^7.0.0
  google_maps_flutter_web: ^0.4.0+3
  google_maps_flutter: ^2.0.3
  flutter_google_places: ^0.3.0
  geocoding: ^2.0.0
  geolocator: ^9.0.2
  shimmer_animation: ^2.0.0
  url_launcher: ^6.0.2
  webview_flutter: ^2.0.2
  firebase_core: ^2.2.0
  firebase_messaging: ^14.1.0
  flutter_local_notifications: ^12.0.3
  path_provider: ^2.0.15
  flutter_html: ^2.2.1
  connectivity: ^3.0.2
  carousel_slider: ^4.0.0-nullsafety.0
  fluro: ^2.0.3
  url_strategy: ^0.2.0
  universal_html: ^2.2.2
  flutter_widget_from_html_core: ^0.9.0
  phone_number: ^1.0.0
  country_code_picker: ^3.0.0
  flutter_typeahead: ^4.3.1
  flutter_inappwebview: ^5.4.3+7
  cached_network_image: ^3.2.1
  audioplayers: ^0.20.1
  #flutter_facebook_auth: ^5.0.6
  google_sign_in: ^5.4.2
  sentry_flutter: ^7.6.2
  new_version: ^0.3.1

#dependency_overrides:
#  package_info_plus_windows: any
#  package_info_plus: any
#  win32: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700